Repository extreme-todo/backend, pull requests merged in 2024-08, with the labels that each got.

#95 Hotfix/94 hotfix api 에러 수정
  src/todo/todo.service.spec.ts
  src/todo/todo.service.ts
Labels: 🚨Hotfix🚨

#97 Update : #96 버전 정보 업데이트 v1.0.0
  package.json
Labels: 🍀Release

#98 v1.0.0 배포
  package.json
  src/app.module.ts
  src/guards/auth.guard.ts
  src/middlewares/verified.middleware.ts
  src/setting/setting.controller.ts
  src/timer/focus.service.ts
  src/timer/rest.service.ts
  src/todo/dto/reorder.dto.ts
  src/todo/dto/todo.dto.ts
  src/todo/dto/update-todo.dto.ts
  src/todo/entities/todo.entity.ts
  src/todo/stubs/todo.stub.ts
  src/todo/todo.controller.ts
  src/todo/todo.service.spec.ts
  src/todo/todo.service.ts
  src/user/auth.service.ts
  src/user/decorators/current-user.decorator.ts
  src/user/stub/user.stub.ts
  src/user/user.controller.ts
  src/utils/testdata/todos.sql
Labels: 🍀Release

#99 Hotfix : #96 테스트 코드 오류 수정
  src/todo/todo.service.spec.ts
Labels: 🍀Release

#100 #96 테스트 코드 오류 수정
  src/todo/todo.service.spec.ts
Labels: 🍀Release

#101 Hotfix : #96 synchronize 옵션 제거
  src/app.module.ts
Labels: 🍀Release

#102 #96 synchronize 옵션 제거 서버 반영
  src/app.module.ts
Labels: 🍀Release

#104 Hotfix/103 removetodosbeforedate 리펙토링 하기
  src/todo/todo.controller.ts
  src/todo/todo.service.spec.ts
  src/todo/todo.service.ts
Labels: 🌟 Refactor, 🚨Hotfix🚨

#106 Update : #103 빼먹은 형변환 추가 및 예외처리
  src/todo/todo.service.ts
Labels: 🚨Hotfix🚨

#107 105 timer 서비스 리팩토링
  package-lock.json
  package.json
  src/app.module.ts
  src/timer/entities/total-focus-time.entity.ts
  src/timer/entities/total-rest-time.entity.ts
  src/timer/focus.service.ts
  src/timer/rest.service.ts
  src/timer/stubs/focusTime.stub.ts
  src/timer/stubs/restTime.stub.ts
  src/timer/timer.controller.ts
  src/timer/timer.module.ts
  src/timer/timer.service.spec.ts
  src/timer/timer.service.ts
  src/todo/todo.module.ts
  src/user/entities/user.entity.ts
  src/user/stub/user.stub.ts
  src/user/user.service.ts
Labels: 🌟 Refactor, 🚨Hotfix🚨
