Repository extreme-todo/backend, pull requests merged in 2024-07, with the labels that each got.

#89 Feature/88 test 과정에서 에러난 부분 수정하기
  src/app.module.ts
  src/todo/dto/todo.dto.ts
  src/todo/dto/update-todo.dto.ts
Labels: ⚙️ API, good first issue

#91 90 db id 값 수정하기
  src/todo/entities/todo.entity.ts
  src/todo/stubs/todo.stub.ts
  src/todo/todo.controller.ts
  src/todo/todo.service.spec.ts
  src/todo/todo.service.ts
  src/user/stub/user.stub.ts
Labels: ✨ Feature

#92 Update : #83 removeTodosBeforeDate 메소드 수정
  src/todo/todo.controller.ts
  src/todo/todo.service.ts
  src/utils/testdata/todos.sql
Labels: ✨ Feature

#93 Fix : #88 timer reset 누락된 column 추가
  src/timer/focus.service.ts
  src/timer/rest.service.ts
Labels: good first issue
